name: reading-time

services:
  reading-time:
    container_name: reading-time
    image: ghcr.io/antoinekahlouche/reading-time:latest
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data:ro
      - reading-time:/tmp/reading-time
    environment:
      PORT: 3000
      DATA_DIR: /app/data
      RENDER_DPI: 120
      JPEG_QUALITY: 85

volumes:
  reading-time:
